services:
  migration:
    image: {{projectName}}:integration
    command: npx prisma migrate deploy
  api:
    image: {{projectName}}:integration
    restart: always
    ports:
      - 3000:3000
  cron:
    image: {{projectName}}:integration
    container_name: {{projectName}}-cron-integration
    command: npx aomex cron:start
