FROM node:{{nodeVersion}}
COPY . /codes
WORKDIR /codes

RUN mv .env.production .env

ENV TZ=Asia/Shanghai
ENV PORT=3000
ENV NODE_ENV=production

RUN sh scripts/build-in-docker.sh

CMD ["node", "--enable-source-maps", "--stack-trace-limit=100", "src/web.js"]
