services:
  migration:
    image: {{projectName}}:production
    command: npx prisma migrate deploy
  api:
    image: {{projectName}}:production
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    ports:
      - 3000:3000
  cron:
    image: {{projectName}}:production
    command: npx aomex cron:start
    restart: always
    environment:
      - NODE_COMPILE_CACHE=/tmp
