services:
  migration:
    image: {{projectName}}:production
    command: npx prisma migrate deploy
  api:
    image: {{projectName}}:production
    restart: always
    ports:
      - 3000:3000
  cron:
    image: {{projectName}}:production
    container_name: {{projectName}}-cron-production
    command: npx aomex cron:start
