FROM node:{{nodeVersion}}
COPY . /codes
WORKDIR /codes

RUN mv .env.production .env

ENV TZ=Asia/Shanghai
ENV PORT=3000
ENV NODE_ENV=production
ENV NODE_OPTIONS='--enable-source-maps --stack-trace-limit=50'

RUN sh scripts/build-in-docker.sh

CMD ["node", "src/web.js"]
