services:
  mysql:
    image: mysql:8
    environment:
      # 对应 .env 文件的配置
      MYSQL_DATABASE: demo_db
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - ./volumes/mysql:/var/lib/mysql
    ports:
      - 3306:3306
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --explicit_defaults_for_timestamp=true
  redis:
    image: redis:7
    volumes:
      - ./volumes/redis:/data
    ports:
      - 6379:6379
