services:
  migration:
    image: {{projectName}}:integration
    command: npx prisma migrate deploy
  api:
    image: {{projectName}}:integration
    ports:
      - 3000:3000
  cron:
    image: {{projectName}}:integration
    command: npx aomex cron:start
    restart: always
    environment:
      - NODE_COMPILE_CACHE=/tmp
