services:
  migration:
    image: {{projectName}}:production
    command: npx prisma migrate deploy
  api:
    image: {{projectName}}:production
    ports:
      - 3000:3000
  cron:
    image: {{projectName}}:production
    command: npx aomex cron:start
    environment:
      - NODE_COMPILE_CACHE=/tmp
