FROM node:{{nodeVersion}}
COPY . /codes
WORKDIR /codes

RUN mv .env.integration .env

ENV TZ=Asia/Shanghai
ENV PORT=3000
ENV NODE_ENV=integration

RUN sh scripts/build-in-docker.sh

CMD ["node", "--enable-source-maps", "src/web.js"]
